---
title: Життя та незвичайні пригоди Дона Карлоса
description: Особистий блоґ
timezone: Europe/Kiev
url: https://kastaneda.kiev.ua
baseurl: ''
lang: uk

exclude:
  - Makefile
  - README
  - kastaneda.kiev.ua.tar.gz
  - build.sh

defaults:
  - scope:
      path: ''
    values:
      layout: page
  - scope:
      type: posts
    values:
      layout: post

collections:
  posts:
    title: Posts
    output: true

sass:
  style: compressed

highlighter: rouge
