---
timezone: Europe/Kiev
url: https://kastaneda.kiev.ua
baseurl: ''
title: Життя та незвичайні пригоди Дона Карлоса
description: Особистий блоґ

exclude:
- Makefile
- README
- kastaneda.kiev.ua.tar.gz
- build.sh

defaults:
- scope:
    path: ''
  values:
    layout: article
- scope:
    type: posts
  values:
    layout: post

collections:
  posts:
    title: Posts
    output: true

sass:
  style: compact

highlighter: rouge

lang: uk

i18n:
  uk:
    title: Життя та незвичайні пригоди Дона Карлоса
    description: Особистий блоґ
    copyrights: © 2001–2021 Дмитро Колесников.
    nav:
    - link: /
      name: На початок
#   - link: /about.uk.html
#     name: Про цей сайт
#   - link: /contacts.uk.html
#     name: Контакти
    - link: /feed.xml
      name: RSS
    - link: https://github.com/kastaneda/kastaneda.kiev.ua/
      name: GitHub

  en:
    title: The life and unusual adventures of Don Karlos
    description: Personal blog
    copyrights: © 2001–2021 Dmytro Kolesnykov.
    nav:
    - link: /
      name: Index
#   - link: /about.en.html
#     name: About this site
#   - link: /contacts.en.html
#     name: Contacts
    - link: /feed.xml
      name: RSS
    - link: https://github.com/kastaneda/kastaneda.kiev.ua/
      name: GitHub

  ru:
    title: Жизнь и необычные приключения Дона Карлоса
    description: Личный блог
    copyrights: © 2001–2021 Дмитрий Колесников.
    nav:
    - link: /
      name: В начало
#   - link: /about.ru.html
#     name: Про этот сайт
#   - link: /contacts.ru.html
#     name: Контакты
    - link: /feed.xml
      name: RSS
    - link: https://github.com/kastaneda/kastaneda.kiev.ua/
      name: GitHub
      
